# Generated by Django 5.0.3 on 2025-02-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('RUB', 'RUB'), ('EUR', 'EUR')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='order',
            name='taxes',
            field=models.ManyToManyField(blank=True, to='payments.tax'),
        ),
    ]
