# Generated by Django 5.0.3 on 2025-02-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_discount_tax_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
