# Generated by Django 5.0.3 on 2025-02-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_tax_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
