# Generated by Django 5.0.3 on 2025-02-24 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_discount_stripe_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discounts',
        ),
        migrations.AlterField(
            model_name='order',
            name='taxes',
            field=models.ManyToManyField(blank=True, null=True, to='payments.tax'),
        ),
        migrations.AddField(
            model_name='order',
            name='discounts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.discount'),
        ),
    ]
