# Generated by Django 5.0.3 on 2025-02-24 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_remove_order_discounts_alter_order_taxes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='discounts',
            new_name='discount',
        ),
    ]
