services:
  db:
    image: postgres:13
    container_name: "ps_postgres"
    env_file: ".env"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}" ]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s



  django:
    container_name: "ps_django"
    build: ./
    command: bash -c "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn --bind 0.0.0.0:8000 --workers ${GUNICORN_WORKERS} payment_system.wsgi:application"
    volumes:
      - ./:/usr/src/app
    depends_on:
      db:
        condition: service_healthy

  nginx:
    container_name: "ps_nginx"
    image: nginx:1.27.4
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./staticfiles:/usr/src/app/staticfiles
    ports:
      - "80:80"
    depends_on:
      - django

volumes:
  postgres_data: